version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "xpack.ml.enabled=false"
  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
      
